name: Cypress Tests Continuos Integration

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.

      - name: Instalar dependências da aplicação
        run: cd hub-de-leitura-integrado && npm install

      - name: Subir aplicação em background
        run: cd hub-de-leitura-integrado && npm start &

      - name: Aguardar aplicação estar pronta
        run: npx wait-on http://localhost:3000

      - name: Instalar dependências dos testes
        run: npm install

      - name: Executar testes Cypress
        run: npx cypress run

      - name: Gerar relatório Allure
        if: always()
        run: npx allure generate allure-results --clean -o allure-report

      - name: Publicar relatório no GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report